---
- name: Install bottle python package
  pip:
    name:
      - botocore
      - boto3

- name: Create a directory if it does not exist
  become_user: true
  ansible.builtin.file:
    path: /home/ubuntu/toolbox-backend
    state: directory
    mode: "0755"

- name: GET/DOWNLOAD file from S3 bucket
  amazon.aws.aws_s3:
    bucket: toolbox-testing-ci
    mode: get
    object: "binary/{{ID:0:7}}"
    dest: "/toolbox-backend"
  register: getresult

- name: Extract S3 Binary
  ansible.builtin.unarchive:
    src: ./toolbox-backend/{{ID:0:7}}
    dest: ./toolbox-backend

- name: "run backend"
  become_user: true
  shell: |
    cd ./toolbox-backend
    npm install
    npm start
