---
- name: Install bottle python package
  pip:
    name:
      - botocore
      - boto3

- name: Create a directory if it does not exist
  become_user: true
  ansible.builtin.file:
    path: /home/ubuntu/toolbox-backend
    state: directory
    mode: "0777"

- name: GET/DOWNLOAD file from S3 bucket
  become_user: true
  amazon.aws.aws_s3:
    bucket: toolbox-testing-ci
    mode: get
    object: "binary/{{ID}}.tar.gz"
    dest: "/toolbox-backend/{{ID}}.tar.gz"
  register: getresult

- name: Extract S3 Binary
  become_user: true
  ansible.builtin.unarchive:
    src: ./toolbox-backend/{{ID}}.tar.gz
    dest: ./toolbox-backend

- name: "run backend"
  become_user: true
  shell: |
    cd ./toolbox-backend
    npm install
    npm start
