# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:15.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - run:
          name: Run Build
          command: npm run build
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: test
          command: |
            echo $(ls)
            echo $(pwd)
      - persist_to_workspace:
          root: .
          paths:
            - .

  s3-upload:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: install tar and gzip
          command: |
            yum install tar -y
            yum install gzip -y
      - run:
          name: compress build
          command: |
            cd ..
            tar -zcvf /tmp/my-app-binary.tar.gz /tmp/myapp
      - run:
          name: Deploy to S3
          command: aws s3 cp /tmp/my-app-binary.tar.gz s3://toolbox-testing-ci/binary/

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  orb-free-workflow:
    jobs:
      - test
      - s3-upload:
          requires:
            - test
