---
- name: Install bottle python package
  pip:
    name:
      - botocore
      - boto3

- name: Create a directory if it does not exist
  become_user: true
  ansible.builtin.file:
    path: /home/ubuntu/toolbox-backend
    state: directory
    mode: "0777"

- name: Extract S3 Binary
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/ubuntu/toolbox-backend/{{ID}}.tar.gz
    dest: /home/ubuntu/toolbox-backend
